services:
  iac:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - ./:/workspace
      - terraform_cache:/root/.terraform.d/plugin-cache
      - terragrunt_cache:/root/.terragrunt-cache
    environment:
      - TF_PLUGIN_CACHE_DIR=/root/.terraform.d/plugin-cache
      - TERRAGRUNT_DOWNLOAD=/root/.terragrunt-cache
    tty: true
volumes:
  terraform_cache:
  terragrunt_cache:
